# 5x5 Crypto

> Ever heard of the 5x5 secret message system? If not, basically it's a 5x5 grid with all letters of the alphabet in order, without k because c is represented to make the k sound only. Google it if you need to. A letter is identified by Row-Column. All values are in caps. Try: 1-3,4-4,2-1,{,4-4,2-3,4-5,3-2,1-2,4-3,_,4-5,3-5,}


Let's create the 5x5 grid using numpy:


In [10]:
import numpy as np

grid = np.arange(65, 90)
grid = grid.reshape(5, 5)
grid = np.where(grid < 75, grid, grid+1)
print(grid)

[[65 66 67 68 69]
 [70 71 72 73 74]
 [76 77 78 79 80]
 [81 82 83 84 85]
 [86 87 88 89 90]]


And now let's try to decrypt the given text:

In [13]:
ciphertext = ["1-3","4-4","2-1","{","4-4","2-3","4-5","3-2","1-2","4-3","_","4-5","3-5", "}"]
plaintext = ""

for char in ciphertext:
  if char == "}" or char == "_" or char == "{":
    plaintext += char
  else:
    xco = int(char[0]) - 1
    yco = int(char[2]) - 1
    plaintext += chr(grid[xco][yco])

print(plaintext)

CTF{THUMBS_UP}
